# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de37f56ed86c98a77537cc9c57adf344f31908883e64d06c304f3699bb8105123110be227a5bab24e4ea1dd06bc888b41e159068611d878fa0ad70822023807d

test:
  secret_key_base: 7ae0c4e822a4537d8afb51c3d79e80ad033f67434bd1bf632fc63aa0de27f264742131b9bc72817dfd3b651f6b453d9829d0a7f688c1ed2b4caefe97345028db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
